In [1]:
pip install folium

Requirement already satisfied: folium in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (0.18.0)
Requirement already satisfied: branca>=0.6.0 in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from folium) (3.1.2)
Requirement already satisfied: numpy in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from folium) (1.24.4)
Requirement already satisfied: requests in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from folium) (2.31.0)
Requirement already satisfied: xyzservices in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from folium) (2025.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from jinja2>=2.9->folium) (2.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from requests->folium) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from requests->folium) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from requests->folium) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\.conda\envs\gputf2.10py3.8\lib\site-packages (from requests->folium) (2023.7.22)
Note: you may need to restart the kernel to use updated packages.

WARNING: There was an error checking the latest version of pip.

In [2]:

import folium
import pandas as pd

# สมมุติว่ามีไฟล์ CSV ที่มีคอลัมน์ 'Latitude' และ 'Longitude'
df = pd.read_csv("E:/Datasets_OpenedSources/ข้อมูลทางกายภาพและตำแหน่งของสถานีสูบน้ำและประตูระบายน้ำ_24052566.csv")
print(df)

     gp_id                       gp_name        gp_type        district  \
0        1            สถานีสูบน้ำพระโขนง      บ่อสูบน้ำ      เขตคลองเตย
1        2     สถานีสูบน้ำอุโมงค์พระโขนง      บ่อสูบน้ำ      เขตคลองเตย
2        3         อาคารรับน้ำไผ่พิทักษ์      บ่อสูบน้ำ      เขตคลองเตย
3        4        อาคารรับน้ำเชื้อพระราม      บ่อสูบน้ำ      เขตคลองเตย
4        5        สถานีสูบน้ำคลองยายล้อม      บ่อสูบน้ำ      เขตคลองเตย
..     ...                           ...            ...             ...
433    434       สถานีสูบน้ำคลองบางปะกอก      บ่อสูบน้ำ  เขตราษฏร์บูรณะ
434    435    สถานีสูบน้ำคลองราษฎร์บูรณะ      บ่อสูบน้ำ  เขตราษฏร์บูรณะ
435    436        สถานีสูบน้ำคลองแจงร้อน      บ่อสูบน้ำ  เขตราษฏร์บูรณะ
436    437  ประตูระบายน้ำคลองข้างโรงแก้ว  ประตูระบายน้ำ  เขตราษฏร์บูรณะ
437    438       ประตูระบายน้ำคลองบางบูน  ประตูระบายน้ำ  เขตราษฏร์บูรณะ

      gp_lat   gp_long gp_gate            gp_pump  gp_total_capacity  \
0    13.7085  100.5953     155   45\n 35(3)+10(5)   45\n 35(3)+10(5)
1    13.7097  100.5951      60          4\n 4(15)          4\n 4(15)
2    13.7341  100.5519       -                  -                  -
3    13.7091  100.5541       -                  -                  -
4    13.7085  100.5945       1         2\n 2(0.5)         2\n 2(0.5)
..       ...       ...     ...                ...                ...
433  13.6841  100.4971       4           2\n 2(2)           2\n 2(2)
434  13.6823  100.5050       6           3\n 3(2)           3\n 3(2)
435  13.6762  100.5210       6           3\n 3(2)           3\n 3(2)
436   13.682  100.5121     0.5  2\n 1(0.3)+1(0.2)  2\n 1(0.3)+1(0.2)
437  13.6815  100.5139       1         2\n 2(0.5)         2\n 2(0.5)

     gp_water_control gp_critical  \
0                -0.8         0.2
1                 NaN         NaN
2    -1.50 ถึง  -1.80         0.2
3                   -           -
4                -0.5         0.2
..                ...         ...
433               NaN         0.6
434               NaN         0.7
435      0.00ถึง+0.40         0.7
436    0.00 ถึง +0.30         0.6
437    0.00 ถึง +0.30         0.6

                                            gp_warning
0                                                    0
1    ควบคุมระดับน้ำที่ประตูระบายน้ำคลองแสนแสบ -0.50...
2                                                    0
3                                                    -
4                                                    0
..                                                 ...
433                                                0.5
434                                                0.6
435                                                0.6
436                                                0.5
437                                                0.5

[438 rows x 12 columns]

In [3]:
#ดู 5 แถวแรกของ DataFrame
df.head()

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning
0,1,สถานีสูบน้ำพระโขนง,บ่อสูบน้ำ,เขตคลองเตย,13.7085,100.5953,155,45\n 35(3)+10(5),45\n 35(3)+10(5),-0.8,0.2,0
1,2,สถานีสูบน้ำอุโมงค์พระโขนง,บ่อสูบน้ำ,เขตคลองเตย,13.7097,100.5951,60,4\n 4(15),4\n 4(15),NaN,NaN,ควบคุมระดับน้ำที่ประตูระบายน้ำคลองแสนแสบ -0.50...
2,3,อาคารรับน้ำไผ่พิทักษ์,บ่อสูบน้ำ,เขตคลองเตย,13.7341,100.5519,-,-,-,-1.50 ถึง -1.80,0.2,0
3,4,อาคารรับน้ำเชื้อพระราม,บ่อสูบน้ำ,เขตคลองเตย,13.7091,100.5541,-,-,-,-,-,-
4,5,สถานีสูบน้ำคลองยายล้อม,บ่อสูบน้ำ,เขตคลองเตย,13.7085,100.5945,1,2\n 2(0.5),2\n 2(0.5),-0.5,0.2,0

In [4]:
#ดู 5 แถวสุดท้ายของ DataFrame
df.tail()

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning
433,434,สถานีสูบน้ำคลองบางปะกอก,บ่อสูบน้ำ,เขตราษฏร์บูรณะ,13.6841,100.4971,4,2\n 2(2),2\n 2(2),NaN,0.6,0.5
434,435,สถานีสูบน้ำคลองราษฎร์บูรณะ,บ่อสูบน้ำ,เขตราษฏร์บูรณะ,13.6823,100.5050,6,3\n 3(2),3\n 3(2),NaN,0.7,0.6
435,436,สถานีสูบน้ำคลองแจงร้อน,บ่อสูบน้ำ,เขตราษฏร์บูรณะ,13.6762,100.5210,6,3\n 3(2),3\n 3(2),0.00ถึง+0.40,0.7,0.6
436,437,ประตูระบายน้ำคลองข้างโรงแก้ว,ประตูระบายน้ำ,เขตราษฏร์บูรณะ,13.682,100.5121,0.5,2\n 1(0.3)+1(0.2),2\n 1(0.3)+1(0.2),0.00 ถึง +0.30,0.6,0.5
437,438,ประตูระบายน้ำคลองบางบูน,ประตูระบายน้ำ,เขตราษฏร์บูรณะ,13.6815,100.5139,1,2\n 2(0.5),2\n 2(0.5),0.00 ถึง +0.30,0.6,0.5

In [5]:
#สรุปชนิดของข้อมูล จำนวน non-null แต่ละคอลัมน์
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438 entries, 0 to 437
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gp_id              438 non-null    int64
 1   gp_name            438 non-null    object
 2   gp_type            438 non-null    object
 3   district           438 non-null    object
 4   gp_lat             438 non-null    object
 5   gp_long            429 non-null    float64
 6   gp_gate            438 non-null    object
 7   gp_pump            438 non-null    object
 8   gp_total_capacity  438 non-null    object
 9   gp_water_control   314 non-null    object
 10  gp_critical        403 non-null    object
 11  gp_warning         438 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 41.2+ KB

In [6]:
# รุปค่าทางสถิติ (เฉพาะตัวเลข เช่น mean, std, min, max ฯลฯ)
df.describe()

            gp_id     gp_long
count  438.000000  429.000000
mean   219.500000  100.550016
std    126.583964    0.104942
min      1.000000  100.329600
25%    110.250000  100.488900
50%    219.500000  100.518700
75%    328.750000  100.603100
max    438.000000  100.928300

In [7]:
#ดูข้อมูลสรุปของคอลัมน์ข้อความด้วย
df.describe(include='all')

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning
count,438.000000,438,438,438,438,429.000000,438,438,438,314,403,438
unique,NaN,437,2,48,380,NaN,62,111,111,70,24,31
top,NaN,ประตูระบายน้ำคลองพลับ,ประตูระบายน้ำ,เขตบางกอกน้อย,13.6815,NaN,-,-,-,-1,0.6,0.5
freq,NaN,2,237,34,3,NaN,166,163,163,85,78,78
mean,219.500000,NaN,NaN,NaN,NaN,100.550016,NaN,NaN,NaN,NaN,NaN,NaN
std,126.583964,NaN,NaN,NaN,NaN,0.104942,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,100.329600,NaN,NaN,NaN,NaN,NaN,NaN
25%,110.250000,NaN,NaN,NaN,NaN,100.488900,NaN,NaN,NaN,NaN,NaN,NaN
50%,219.500000,NaN,NaN,NaN,NaN,100.518700,NaN,NaN,NaN,NaN,NaN,NaN
75%,328.750000,NaN,NaN,NaN,NaN,100.603100,NaN,NaN,NaN,NaN,NaN,NaN
max,438.000000,NaN,NaN,NaN,NaN,100.928300,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# ดูจำนวนแถว x คอลัมน์
df.shape

(438, 12)

In [9]:
# รายชื่อคอลัมน์ทั้งหมด
df.columns

Index(['gp_id', 'gp_name', 'gp_type', 'district', 'gp_lat', 'gp_long',
       'gp_gate', 'gp_pump', 'gp_total_capacity', 'gp_water_control',
       'gp_critical', 'gp_warning'],
      dtype='object')

In [10]:
# ดูจำนวน NaN ในแต่ละคอลัมน์
df.isnull().sum()

gp_id                  0
gp_name                0
gp_type                0
district               0
gp_lat                 0
gp_long                9
gp_gate                0
gp_pump                0
gp_total_capacity      0
gp_water_control     124
gp_critical           35
gp_warning             0
dtype: int64

In [11]:
# ดูจำนวนค่าที่ไม่ซ้ำในแต่ละคอลัมน์
df.nunique()

gp_id                438
gp_name              437
gp_type                2
district              48
gp_lat               380
gp_long              377
gp_gate               62
gp_pump              111
gp_total_capacity    111
gp_water_control      70
gp_critical           24
gp_warning            31
dtype: int64

In [12]:
df['gp_name'].value_counts()

gp_name
ประตูระบายน้ำคลองพลับ                             2
สถานีสูบน้ำพระโขนง                                1
สถานีสูบน้ำคลองบางแค \n (ตอนคลองพระยาราชมนตรี)    1
สถานีสูบน้ำคลองรางขี้เหล็ก                        1
ประตูระบายน้ำคลองบางจาก                           1
                                                 ..
ประตูระบายน้ำคลองบางนา                            1
สถานีสูบน้ำคลองวัดโยธินประดิษฐ์                   1
สถานีสูบน้ำบางนา                                  1
สถานีสูบน้ำบางอ้อ                                 1
ประตูระบายน้ำคลองบางบูน                           1
Name: count, Length: 437, dtype: int64

In [13]:
df[df['gp_name'] == 'ประตูระบายน้ำคลองพลับ']

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning
98,99,ประตูระบายน้ำคลองพลับ,ประตูระบายน้ำ,เขตวังทองหลาง,13.7565,100.5989,-,-,-,NaN,NaN,ประตูระบายน้ำ เปิด - ปิด ตามสภาพน้ำและระดับน้ำ
109,110,ประตูระบายน้ำคลองพลับ,ประตูระบายน้ำ,เขตคลองเตย,13.7565,100.5989,0.2,1\n 1(0.20),1\n 1(0.20),-1,0.2,0

In [14]:
df['gp_lat'].value_counts()

gp_lat
13.6815    3
13.7091    3
13.7788    3
13.7842    3
13.6869    3
          ..
13.763     1
13.7608    1
13.7594    1
13.6593    1
13.6762    1
Name: count, Length: 380, dtype: int64

In [15]:
df['gp_long'].value_counts()

gp_long
100.4983    3
100.4902    3
100.5497    2
100.6501    2
100.5410    2
           ..
100.6489    1
100.6469    1
100.6411    1
100.6328    1
100.5139    1
Name: count, Length: 377, dtype: int64

In [16]:
df[df['gp_lat'] == '13.6815']

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning
272,273,สถานีสูบน้ำคลองวัดสิงห์,บ่อสูบน้ำ,เขตบางขุนเทียน,13.6815,100.4478,9,3\n 3(3),3\n 3(3),-0.20 ถึง 0.00,0.4,0.3
294,295,ประตูระบายน้ำคลองมหาศร,ประตูระบายน้ำ,เขตหนองแขม,13.6815,100.3504,-,-,-,NaN,0.7,0.6
437,438,ประตูระบายน้ำคลองบางบูน,ประตูระบายน้ำ,เขตราษฏร์บูรณะ,13.6815,100.5139,1,2\n 2(0.5),2\n 2(0.5),0.00 ถึง +0.30,0.6,0.5

In [17]:
df.iloc[95:103]

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning
95,96,สถานีสูบน้ำคลองวัดตึก,บ่อสูบน้ำ,เขตวังทองหลาง,13.761,100.6117,8,4\n 4(2),4\n 4(2),-0.8,0,-0.2
96,97,สถานีสูบน้ำเจ้าคุณสิงห์,บ่อสูบน้ำ,เขตวังทองหลาง,13.7614,100.6152,9,4\n 1(3)+3(2),4\n 1(3)+3(2),-1,-0.2,-0.3
97,98,สถานีสูบน้ำลำรางกระบือ \n (ตอนคลองแสนแสบ),บ่อสูบน้ำ,เขตวังทองหลาง,13.7572,100.6103,2,2\n 2(1),2\n 2(1),-0.8,0,-0.2
98,99,ประตูระบายน้ำคลองพลับ,ประตูระบายน้ำ,เขตวังทองหลาง,13.7565,100.5989,-,-,-,NaN,NaN,ประตูระบายน้ำ เปิด - ปิด ตามสภาพน้ำและระดับน้ำ
99,100,ประตูระบายน้ำคลองพลับพลา \n ตอนคลองแสนแสบ,ประตูระบายน้ำ,เขตวังทองหลาง,13.7542,100.6071,-,-,-,NaN,NaN,ประตูระบายน้ำ เปิด - ปิด ตามสภาพน้ำและระดับน้ำ
100,101,สถานีสูบน้ำคลองพลับพลา \n (ตอนคลองลาดพร้าว),บ่อสูบน้ำ,เขตวังทองหลาง,13.7635,100.5959,3,3\n 3(1),3\n 3(1),-0.8,0,-0.2
101,102,สถานีสูบน้ำคลองบางเขน-ขาออก\n (ฝั่งเหนือ),บ่อสูบน้ำ,เขตหลักสี่,13.8559,100.5656,1.5,3\n 1(1)+2(0.25),3\n 1(1)+2(0.25),-0.80 ถึง \n -0.30,0.1,0
102,103,สถานีสูบน้ำคลองวัดหลักสี่-ขาเข้า,บ่อสูบน้ำ,เขตหลักสี่,13.8903,100.5854,8,5\n 3(2)+2(1),5\n 3(2)+2(1),-1,0.5,0.4

In [18]:
df.gp_lat

0      13.7085
1      13.7097
2      13.7341
3      13.7091
4      13.7085
        ...
433    13.6841
434    13.6823
435    13.6762
436     13.682
437    13.6815
Name: gp_lat, Length: 438, dtype: object

In [19]:
df.iloc[[343, 344, 345, 289, 212, 233, 24, 86, 25]]

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning
343,344,ประตูระบายน้ำคลองรางจาก,ประตูระบายน้ำ,เขตทุ่งครุ,0-2426-0372,NaN,-,-,-,ปิดประตูเมื่อน้ำเค็ม,0.6,0.55
344,345,ประตูระบายน้ำคลองรางตรง,ประตูระบายน้ำ,เขตทุ่งครุ,0-2457-4078/\n 0-2457-4079,NaN,-,-,-,ปิดประตูเมื่อน้ำเค็ม,0.7,0.6
345,346,ประตูระบายน้ำคลองหนองรี,ประตูระบายน้ำ,เขตทุ่งครุ,0-2457-4078/\n 0-2457-4079,NaN,-,-,-,ปิดประตูเมื่อน้ำเค็ม,0.7,0.6
289,290,สถานีสูบน้ำคลองบางแค \n (ตอนคลองพระยาราชมนตรี),บ่อสูบน้ำ,เขตบางแค,ไม่เกินระดับน้ำเตือนภัย,NaN,3,2\n 2(1.5),2\n 2(1.5),NaN,ไม่เกินระดับน้ำเตือนภัย,ประตูเปิดตลอด
212,213,ประตูระบายน้ำลำรางสาธารณะ\n (ตอนบึงกุ่ม นวมินท...,ประตูระบายน้ำ,เขตบึงกุ่ม,0.2,NaN,-,-,-,เปิด-ปิดตามสภาพน้ำและระดับน้ำ,0.2,0
233,234,ประตูระบายน้ำคลองหลอแหล 2,ประตูระบายน้ำ,เขตมีนบุรี,0-2543-8365,NaN,-,0.2,0.2,0.1,0,0.3
24,25,อาคารรับน้ำบึงมักกะสัน,บ่อสูบน้ำ,เขตราชเทวี,0-2248-1507,NaN,-,0,0,NaN,-1.50 ถึง -1.80,0.1
86,87,ประตูระบายน้ำบึงมักกะสัน \n (ด้านทิศตะวันออก),ประตูระบายน้ำ,เขตราชเทวี,0-2247-1321,NaN,-,0.5,0.5,ปิด,ปิด,0.6
25,26,ประตูระบายน้ำลาดพร้าว 56,ประตูระบายน้ำ,เขตวังทองหลาง,0-2541-1933,NaN,-,-,-,ประตูระบายน้ำ เปิด-ปิด \n ตามสภาพน้ำและระดับน้ำ,0.4,0.2

In [20]:
df.iloc[[343, 344, 345, 289, 212, 233, 24, 86, 25]][['gp_id', 'gp_name', 'gp_lat', 'gp_long']]

,gp_id,gp_name,gp_lat,gp_long
343,344,ประตูระบายน้ำคลองรางจาก,0-2426-0372,NaN
344,345,ประตูระบายน้ำคลองรางตรง,0-2457-4078/\n 0-2457-4079,NaN
345,346,ประตูระบายน้ำคลองหนองรี,0-2457-4078/\n 0-2457-4079,NaN
289,290,สถานีสูบน้ำคลองบางแค \n (ตอนคลองพระยาราชมนตรี),ไม่เกินระดับน้ำเตือนภัย,NaN
212,213,ประตูระบายน้ำลำรางสาธารณะ\n (ตอนบึงกุ่ม นวมินท...,0.2,NaN
233,234,ประตูระบายน้ำคลองหลอแหล 2,0-2543-8365,NaN
24,25,อาคารรับน้ำบึงมักกะสัน,0-2248-1507,NaN
86,87,ประตูระบายน้ำบึงมักกะสัน \n (ด้านทิศตะวันออก),0-2247-1321,NaN
25,26,ประตูระบายน้ำลาดพร้าว 56,0-2541-1933,NaN

In [21]:
df2 = df.copy()
df2

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning
0,1,สถานีสูบน้ำพระโขนง,บ่อสูบน้ำ,เขตคลองเตย,13.7085,100.5953,155,45\n 35(3)+10(5),45\n 35(3)+10(5),-0.8,0.2,0
1,2,สถานีสูบน้ำอุโมงค์พระโขนง,บ่อสูบน้ำ,เขตคลองเตย,13.7097,100.5951,60,4\n 4(15),4\n 4(15),NaN,NaN,ควบคุมระดับน้ำที่ประตูระบายน้ำคลองแสนแสบ -0.50...
2,3,อาคารรับน้ำไผ่พิทักษ์,บ่อสูบน้ำ,เขตคลองเตย,13.7341,100.5519,-,-,-,-1.50 ถึง -1.80,0.2,0
3,4,อาคารรับน้ำเชื้อพระราม,บ่อสูบน้ำ,เขตคลองเตย,13.7091,100.5541,-,-,-,-,-,-
4,5,สถานีสูบน้ำคลองยายล้อม,บ่อสูบน้ำ,เขตคลองเตย,13.7085,100.5945,1,2\n 2(0.5),2\n 2(0.5),-0.5,0.2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,สถานีสูบน้ำคลองบางปะกอก,บ่อสูบน้ำ,เขตราษฏร์บูรณะ,13.6841,100.4971,4,2\n 2(2),2\n 2(2),NaN,0.6,0.5
434,435,สถานีสูบน้ำคลองราษฎร์บูรณะ,บ่อสูบน้ำ,เขตราษฏร์บูรณะ,13.6823,100.5050,6,3\n 3(2),3\n 3(2),NaN,0.7,0.6
435,436,สถานีสูบน้ำคลองแจงร้อน,บ่อสูบน้ำ,เขตราษฏร์บูรณะ,13.6762,100.5210,6,3\n 3(2),3\n 3(2),0.00ถึง+0.40,0.7,0.6
436,437,ประตูระบายน้ำคลองข้างโรงแก้ว,ประตูระบายน้ำ,เขตราษฏร์บูรณะ,13.682,100.5121,0.5,2\n 1(0.3)+1(0.2),2\n 1(0.3)+1(0.2),0.00 ถึง +0.30,0.6,0.5
437,438,ประตูระบายน้ำคลองบางบูน,ประตูระบายน้ำ,เขตราษฏร์บูรณะ,13.6815,100.5139,1,2\n 2(0.5),2\n 2(0.5),0.00 ถึง +0.30,0.6,0.5

In [22]:
# ปรับปรุงข้อมูลคอลัมน์ gp_lat
# 1.ย้ายค่าจาก gp_lat → ไปไว้ใน gp_phone เฉพาะแถวที่ระบุ

# 2.แทนค่า gp_lat เดิมด้วย NaN เฉพาะแถวนั้น


import numpy as np
#copy df
df2 = df.copy()
# รายการ index ของแถวที่ต้องการย้าย
rows_to_move = [343, 344, 345, 289, 212, 233, 24, 86, 25]

# สร้างคอลัมน์ใหม่ 'gp_phone' ถ้ายังไม่มี
if 'gp_phone' not in df2.columns:
    df2['gp_phone'] = np.nan

# ย้ายข้อมูลจาก gp_lat ไปยัง gp_phone
df2.loc[rows_to_move, 'gp_phone'] = df2.loc[rows_to_move, 'gp_lat']

# แทนค่าที่ gp_lat ด้วย NaN
df2.loc[rows_to_move, 'gp_lat'] = np.nan

df2

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning,gp_phone
0,1,สถานีสูบน้ำพระโขนง,บ่อสูบน้ำ,เขตคลองเตย,13.7085,100.5953,155,45\n 35(3)+10(5),45\n 35(3)+10(5),-0.8,0.2,0,NaN
1,2,สถานีสูบน้ำอุโมงค์พระโขนง,บ่อสูบน้ำ,เขตคลองเตย,13.7097,100.5951,60,4\n 4(15),4\n 4(15),NaN,NaN,ควบคุมระดับน้ำที่ประตูระบายน้ำคลองแสนแสบ -0.50...,NaN
2,3,อาคารรับน้ำไผ่พิทักษ์,บ่อสูบน้ำ,เขตคลองเตย,13.7341,100.5519,-,-,-,-1.50 ถึง -1.80,0.2,0,NaN
3,4,อาคารรับน้ำเชื้อพระราม,บ่อสูบน้ำ,เขตคลองเตย,13.7091,100.5541,-,-,-,-,-,-,NaN
4,5,สถานีสูบน้ำคลองยายล้อม,บ่อสูบน้ำ,เขตคลองเตย,13.7085,100.5945,1,2\n 2(0.5),2\n 2(0.5),-0.5,0.2,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,สถานีสูบน้ำคลองบางปะกอก,บ่อสูบน้ำ,เขตราษฏร์บูรณะ,13.6841,100.4971,4,2\n 2(2),2\n 2(2),NaN,0.6,0.5,NaN
434,435,สถานีสูบน้ำคลองราษฎร์บูรณะ,บ่อสูบน้ำ,เขตราษฏร์บูรณะ,13.6823,100.5050,6,3\n 3(2),3\n 3(2),NaN,0.7,0.6,NaN
435,436,สถานีสูบน้ำคลองแจงร้อน,บ่อสูบน้ำ,เขตราษฏร์บูรณะ,13.6762,100.5210,6,3\n 3(2),3\n 3(2),0.00ถึง+0.40,0.7,0.6,NaN
436,437,ประตูระบายน้ำคลองข้างโรงแก้ว,ประตูระบายน้ำ,เขตราษฏร์บูรณะ,13.682,100.5121,0.5,2\n 1(0.3)+1(0.2),2\n 1(0.3)+1(0.2),0.00 ถึง +0.30,0.6,0.5,NaN
437,438,ประตูระบายน้ำคลองบางบูน,ประตูระบายน้ำ,เขตราษฏร์บูรณะ,13.6815,100.5139,1,2\n 2(0.5),2\n 2(0.5),0.00 ถึง +0.30,0.6,0.5,NaN

In [23]:
df2.iloc[[343, 344, 345, 289, 212, 233, 24, 86, 25]][['gp_id', 'gp_name', 'gp_lat', 'gp_long', 'gp_phone']]

,gp_id,gp_name,gp_lat,gp_long,gp_phone
343,344,ประตูระบายน้ำคลองรางจาก,NaN,NaN,0-2426-0372
344,345,ประตูระบายน้ำคลองรางตรง,NaN,NaN,0-2457-4078/\n 0-2457-4079
345,346,ประตูระบายน้ำคลองหนองรี,NaN,NaN,0-2457-4078/\n 0-2457-4079
289,290,สถานีสูบน้ำคลองบางแค \n (ตอนคลองพระยาราชมนตรี),NaN,NaN,ไม่เกินระดับน้ำเตือนภัย
212,213,ประตูระบายน้ำลำรางสาธารณะ\n (ตอนบึงกุ่ม นวมินท...,NaN,NaN,0.2
233,234,ประตูระบายน้ำคลองหลอแหล 2,NaN,NaN,0-2543-8365
24,25,อาคารรับน้ำบึงมักกะสัน,NaN,NaN,0-2248-1507
86,87,ประตูระบายน้ำบึงมักกะสัน \n (ด้านทิศตะวันออก),NaN,NaN,0-2247-1321
25,26,ประตูระบายน้ำลาดพร้าว 56,NaN,NaN,0-2541-1933

In [24]:
df.iloc[[343, 344, 345, 289, 212, 233, 24, 86, 25]][['gp_id', 'gp_name', 'gp_lat', 'gp_long']]

,gp_id,gp_name,gp_lat,gp_long
343,344,ประตูระบายน้ำคลองรางจาก,0-2426-0372,NaN
344,345,ประตูระบายน้ำคลองรางตรง,0-2457-4078/\n 0-2457-4079,NaN
345,346,ประตูระบายน้ำคลองหนองรี,0-2457-4078/\n 0-2457-4079,NaN
289,290,สถานีสูบน้ำคลองบางแค \n (ตอนคลองพระยาราชมนตรี),ไม่เกินระดับน้ำเตือนภัย,NaN
212,213,ประตูระบายน้ำลำรางสาธารณะ\n (ตอนบึงกุ่ม นวมินท...,0.2,NaN
233,234,ประตูระบายน้ำคลองหลอแหล 2,0-2543-8365,NaN
24,25,อาคารรับน้ำบึงมักกะสัน,0-2248-1507,NaN
86,87,ประตูระบายน้ำบึงมักกะสัน \n (ด้านทิศตะวันออก),0-2247-1321,NaN
25,26,ประตูระบายน้ำลาดพร้าว 56,0-2541-1933,NaN

In [25]:
df2.iloc[[212, 289]]

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning,gp_phone
212,213,ประตูระบายน้ำลำรางสาธารณะ\n (ตอนบึงกุ่ม นวมินท...,ประตูระบายน้ำ,เขตบึงกุ่ม,NaN,NaN,-,-,-,เปิด-ปิดตามสภาพน้ำและระดับน้ำ,0.2,0,0.2
289,290,สถานีสูบน้ำคลองบางแค \n (ตอนคลองพระยาราชมนตรี),บ่อสูบน้ำ,เขตบางแค,NaN,NaN,3,2\n 2(1.5),2\n 2(1.5),NaN,ไม่เกินระดับน้ำเตือนภัย,ประตูเปิดตลอด,ไม่เกินระดับน้ำเตือนภัย

In [26]:
# ลบค่าคอลัมน์ gp_phone ของแถวที่ index 212 และ 289
df2.loc[[212, 289], 'gp_phone'] = np.nan
df2.iloc[[212, 289]]

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning,gp_phone
212,213,ประตูระบายน้ำลำรางสาธารณะ\n (ตอนบึงกุ่ม นวมินท...,ประตูระบายน้ำ,เขตบึงกุ่ม,NaN,NaN,-,-,-,เปิด-ปิดตามสภาพน้ำและระดับน้ำ,0.2,0,NaN
289,290,สถานีสูบน้ำคลองบางแค \n (ตอนคลองพระยาราชมนตรี),บ่อสูบน้ำ,เขตบางแค,NaN,NaN,3,2\n 2(1.5),2\n 2(1.5),NaN,ไม่เกินระดับน้ำเตือนภัย,ประตูเปิดตลอด,NaN

In [27]:
df2.iloc[[343, 344, 345, 289, 212, 233, 24, 86, 25]]

,gp_id,gp_name,gp_type,district,gp_lat,gp_long,gp_gate,gp_pump,gp_total_capacity,gp_water_control,gp_critical,gp_warning,gp_phone
343,344,ประตูระบายน้ำคลองรางจาก,ประตูระบายน้ำ,เขตทุ่งครุ,NaN,NaN,-,-,-,ปิดประตูเมื่อน้ำเค็ม,0.6,0.55,0-2426-0372
344,345,ประตูระบายน้ำคลองรางตรง,ประตูระบายน้ำ,เขตทุ่งครุ,NaN,NaN,-,-,-,ปิดประตูเมื่อน้ำเค็ม,0.7,0.6,0-2457-4078/\n 0-2457-4079
345,346,ประตูระบายน้ำคลองหนองรี,ประตูระบายน้ำ,เขตทุ่งครุ,NaN,NaN,-,-,-,ปิดประตูเมื่อน้ำเค็ม,0.7,0.6,0-2457-4078/\n 0-2457-4079
289,290,สถานีสูบน้ำคลองบางแค \n (ตอนคลองพระยาราชมนตรี),บ่อสูบน้ำ,เขตบางแค,NaN,NaN,3,2\n 2(1.5),2\n 2(1.5),NaN,ไม่เกินระดับน้ำเตือนภัย,ประตูเปิดตลอด,NaN
212,213,ประตูระบายน้ำลำรางสาธารณะ\n (ตอนบึงกุ่ม นวมินท...,ประตูระบายน้ำ,เขตบึงกุ่ม,NaN,NaN,-,-,-,เปิด-ปิดตามสภาพน้ำและระดับน้ำ,0.2,0,NaN
233,234,ประตูระบายน้ำคลองหลอแหล 2,ประตูระบายน้ำ,เขตมีนบุรี,NaN,NaN,-,0.2,0.2,0.1,0,0.3,0-2543-8365
24,25,อาคารรับน้ำบึงมักกะสัน,บ่อสูบน้ำ,เขตราชเทวี,NaN,NaN,-,0,0,NaN,-1.50 ถึง -1.80,0.1,0-2248-1507
86,87,ประตูระบายน้ำบึงมักกะสัน \n (ด้านทิศตะวันออก),ประตูระบายน้ำ,เขตราชเทวี,NaN,NaN,-,0.5,0.5,ปิด,ปิด,0.6,0-2247-1321
25,26,ประตูระบายน้ำลาดพร้าว 56,ประตูระบายน้ำ,เขตวังทองหลาง,NaN,NaN,-,-,-,ประตูระบายน้ำ เปิด-ปิด \n ตามสภาพน้ำและระดับน้ำ,0.4,0.2,0-2541-1933

In [28]:
import folium
import pandas as pd

### folium.Marker() ไม่สามารถพล็อตจุดที่ไม่มีพิกัดได้ (จำเป็นต้องมีค่าตัวเลข)

# อ่านข้อมูลจากไฟล์ CSV
#df = pd.read_csv('locations.csv')
df2

# สร้างแผนที่ centered ที่ประเทศไทย (กรุงเทพฯ)
m = folium.Map(location=[13.75, 100.5], zoom_start=6)

# วนลูปเพิ่ม marker ตามพิกัด
for i, row in df2.iterrows():
    folium.Marker(
        location=[row['gp_lat'], row['gp_long']],
        popup=row['gp_name']
    ).add_to(m)

# บันทึกเป็น HTML เพื่อเปิดดูในเบราว์เซอร์
m.save('flood_way_thailand_map.html')

ValueError: Location values cannot contain NaNs.

In [ ]:
# วิธีแก้ไข: กรองแถวที่ gp_lat และ gp_long ไม่เป็น NaN ก่อนวนลูป
df_valid = df2.dropna(subset=['gp_lat', 'gp_long'])

for i, row in df_valid.iterrows():
    folium.Marker(
        location=[row['gp_lat'], row['gp_long']],
        popup=row['gp_name']
    ).add_to(m)
    
# บันทึกเป็น HTML เพื่อเปิดดูในเบราว์เซอร์
# save ในไดรฟ์ C:\Users\PC
# m.save('flood_way_thailand_map.html') 

# save ในไดรฟ์ E:
m.save('E:/Datasets_OpenedSources/flood_way_thailand_map.html')

In [ ]:
#pyhton เปิดไฟล์แผนที่

import webbrowser
webbrowser.open('E:/Datasets_OpenedSources/flood_way_thailand_map.html')

# เพิ่ม ข้อความหลังชี้ที่หมุดแผนที่

In [ ]:
for i, row in df_valid.iterrows():
    folium.Marker(
        location=[row['gp_lat'], row['gp_long']],
        popup=row['gp_name'],
        popup_text = f"{row['gp_name']}<br>ชนิด: {row['gp_type']}<br>เขต: {row['district']}<br>การควบคุม: {row['gp_water_control']}<br>ระดับการเตือน: {row['gp_warning']}<br>จุดวิกฤต: {row['gp_critical']}<br>โทรศัพท์: {row['gp_phone']}"
    ).add_to(m)
    
# บันทึกเป็น HTML เพื่อเปิดดูในเบราว์เซอร์
# save ในไดรฟ์ C:\Users\PC
# m.save('flood_way_thailand_map.html') 

# save ในไดรฟ์ E:
m.save('E:/Datasets_OpenedSources/flood_way_thailand_map.html')

In [ ]:
#pyhton เปิดไฟล์แผนที่

import webbrowser
webbrowser.open('E:/Datasets_OpenedSources/flood_way_thailand_map.html')

In [ ]:
for i, row in df_valid.iterrows():
    popup_text = f"""
        <b>{row['gp_name']}</b><br>
        ชนิด: {row['gp_type']}<br>
        เขต: {row['district']}<br>
        ระดับการควบคุม: {row['gp_water_control']}<br>
        ระดับการเตือน: {row['gp_warning']}<br>
        จุดวิกฤต: {row['gp_critical']}<br>
        โทรศัพท์: {row['gp_phone']}
    """

    folium.Marker(
        location=[row['gp_lat'], row['gp_long']],
        popup=folium.Popup(popup_text, max_width=300),
        tooltip=row['gp_name']  # ชื่อจะแสดงตอนเอาเมาส์ชี้
    ).add_to(m)
    
# save ในไดรฟ์ E:
m.save('E:/Datasets_OpenedSources/flood_way_thailand_map_popuptext.html')

webbrowser.open('E:/Datasets_OpenedSources/flood_way_thailand_map_popuptext.html')

In [ ]:
for i, row in df_valid.iterrows():
    popup_text = f"""
        {row['gp_name']}
        | ชนิด: {row['gp_type']}
        | เขต: {row['district']}
        | ระดับการควบคุม: {row['gp_water_control']}
        | ระดับการเตือน: {row['gp_warning']}
        | จุดวิกฤต: {row['gp_critical']}

    """
        #| โทรศัพท์: {row['gp_phone']}
        
    folium.Marker(
        location=[row['gp_lat'], row['gp_long']],
        popup=folium.Popup(popup_text.replace('|', '<br>'), max_width=300),  # ใช้ HTML ใน popup
        tooltip=popup_text  # แสดงข้อความทั้งหมดตอนชี้เมาส์
    ).add_to(m)
    
    # save ในไดรฟ์ E:
m.save('E:/Datasets_OpenedSources/flood_way_thailand_map_popuptext.html')

webbrowser.open('E:/Datasets_OpenedSources/flood_way_thailand_map_popuptext.html')